# Generated by Django 5.2.8 on 2025-12-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('leave_applied', 'Leave Applied'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('regularization_applied', 'Regularization Applied'), ('regularization_approved', 'Regularization Approved'), ('regularization_rejected', 'Regularization Rejected')], default='system', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
