# Generated by Django 5.2.8 on 2025-12-01 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='father_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pan_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('leave_applied', 'Leave Applied'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('regularization_applied', 'Regularization Applied'), ('regularization_approved', 'Regularization Approved'), ('regularization_rejected', 'Regularization Rejected'), ('profile_update_requested', 'Profile Update Requested'), ('profile_update_approved', 'Profile Update Approved'), ('profile_update_rejected', 'Profile Update Rejected')], default='system', max_length=30),
        ),
        migrations.CreateModel(
            name='ProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_name', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('requested_father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_father_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('requested_aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('requested_pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('requested_bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('requested_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_bank_ifsc', models.CharField(blank=True, max_length=11, null=True)),
                ('requested_address', models.TextField(blank=True, null=True)),
                ('requested_photo', models.ImageField(blank=True, null=True, upload_to='profile_update_requests/photos/')),
                ('requested_aadhaar_photo', models.ImageField(blank=True, null=True, upload_to='profile_update_requests/aadhaar/')),
                ('requested_pan_photo', models.ImageField(blank=True, null=True, upload_to='profile_update_requests/pan/')),
                ('changed_fields', models.TextField(help_text='Comma-separated list of fields being changed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for update request')),
                ('review_remarks', models.TextField(blank=True)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profile_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_update_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_update_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
