# Generated by Django 5.2.8 on 2025-12-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_aadhaar_number_user_aadhaar_photo_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupdaterequest',
            name='requested_bank_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_holder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
