# Generated by Django 5.0.1 on 2025-12-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('leave_applied', 'Leave Applied'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('regularization_applied', 'Regularization Applied'), ('regularization_approved', 'Regularization Approved'), ('regularization_rejected', 'Regularization Rejected'), ('profile_update_requested', 'Profile Update Requested'), ('profile_update_approved', 'Profile Update Approved'), ('profile_update_rejected', 'Profile Update Rejected'), ('wfh_applied', 'WFH Applied'), ('wfh_approved', 'WFH Approved'), ('wfh_rejected', 'WFH Rejected'), ('holiday', 'Holiday')], default='system', max_length=30),
        ),
    ]
