# Generated by Django 5.2.8 on 2025-12-01 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_meters', models.IntegerField(default=50)),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'office_locations',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('punch_in', models.DateTimeField(blank=True, null=True)),
                ('punch_out', models.DateTimeField(blank=True, null=True)),
                ('punch_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('punch_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('punch_out_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('punch_out_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('punch_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('punch_out_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='present', max_length=20)),
                ('working_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', '-punch_in'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
