# Generated by Django 5.2.8 on 2025-12-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_off_day',
            field=models.BooleanField(default=False, help_text='True if employee worked on their weekly off day'),
        ),
    ]
