# Generated by Django 5.2.8 on 2025-12-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_regularizationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_auto_punch_out',
            field=models.BooleanField(default=False, help_text='True if system auto punched out at 11 PM'),
        ),
    ]
