# Generated by Django 5.0.1 on 2025-12-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_is_wfh_wfhrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officelocation',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
