# Generated by Django 5.0.1 on 2025-12-02 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_shift_compoff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'date'], name='attendance_user_id_d716c4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='attendance_date_32df9b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'status', 'date'], name='attendance_user_id_1798a7_idx'),
        ),
        migrations.AddIndex(
            model_name='compoff',
            index=models.Index(fields=['user', 'status'], name='comp_offs_user_id_cf5e33_idx'),
        ),
        migrations.AddIndex(
            model_name='compoff',
            index=models.Index(fields=['user', 'earned_date'], name='comp_offs_user_id_bde6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='compoff',
            index=models.Index(fields=['status', 'expires_on'], name='comp_offs_status_d3f2d1_idx'),
        ),
    ]
