# Generated by Django 5.2.8 on 2025-12-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='lop_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='paid_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
