# Generated by Django 5.2.8 on 2025-12-01 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_add_sick_leave_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_leaves',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('user', 'leave_type', 'year', 'month')},
        ),
    ]
