# Generated by Django 5.0.1 on 2025-12-02 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_leaverequest_comp_off_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['user', 'year', 'month'], name='leave_balan_user_id_d4310a_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['user', 'leave_type', 'year'], name='leave_balan_user_id_8cd8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['user', 'status'], name='leave_reque_user_id_487b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['user', 'start_date', 'end_date'], name='leave_reque_user_id_59eee3_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'start_date'], name='leave_reque_status_cccf6b_idx'),
        ),
    ]
